# Generated by Django 4.0.6 on 2022-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100)),
                ('km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observatii', models.CharField(max_length=100)),
            ],
        ),
    ]
