# Generated by Django 4.0.6 on 2022-10-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_postform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
