# Generated by Django 4.0.6 on 2022-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_postform_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontaj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=100)),
                ('km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observatii', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontajToggleEdit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pontaj_id', models.IntegerField(null=True)),
                ('is_edit_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
