# Generated by Django 4.0.6 on 2022-12-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_postform_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontajToggleEdit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pontaj_id', models.IntegerField(null=True)),
                ('is_edit_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
