# Generated by Django 4.0.6 on 2022-12-22 12:17

import administrator.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_pontajtoggleedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontaj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=100)),
                ('km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observatii', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime(2022, 12, 22, 12, 17, 22, 685540, tzinfo=utc))),
                ('updated_at', administrator.models.AutoDateTimeField(default=datetime.datetime(2022, 12, 22, 12, 17, 22, 685909, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Postform',
        ),
    ]
