# Generated by Django 4.0.6 on 2022-12-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_pontaj_pontajtoggleedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masini',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numar', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Postform',
        ),
    ]
