# Generated by Django 4.0.6 on 2022-12-22 12:19

import administrator.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_pontaj_delete_postform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontaj',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 12, 19, 49, 953804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='updated_at',
            field=administrator.models.AutoDateTimeField(default=datetime.datetime(2022, 12, 22, 12, 19, 49, 954187, tzinfo=utc)),
        ),
    ]
