# Generated by Django 4.0.6 on 2022-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_masini_delete_postform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuscareMembriiEchipei',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puscare_id', models.IntegerField()),
                ('nume_membru', models.CharField(max_length=150)),
                ('masina_membru', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puscari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cariera', models.CharField(max_length=150)),
                ('ora', models.TimeField()),
                ('nume_coordonator', models.CharField(max_length=150)),
                ('masina_coordonator', models.CharField(max_length=150)),
                ('nume_artificier', models.CharField(max_length=150)),
                ('masina_artificier', models.CharField(max_length=150)),
                ('nume_azot', models.CharField(max_length=150)),
                ('masina_azot', models.CharField(max_length=150)),
                ('membrii_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
