# Generated by Django 4.0.6 on 2022-12-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_puscaremembriiechipei_puscari'),
    ]

    operations = [
        migrations.AddField(
            model_name='puscari',
            name='ziua',
            field=models.DateField(null=True),
        ),
    ]
