# Generated by Django 4.0.6 on 2022-12-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_puscari_ziua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puscari',
            name='membrii_id',
        ),
        migrations.AddField(
            model_name='puscari',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
