# Generated by Django 4.0.6 on 2022-12-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_remove_puscari_membrii_id_puscari_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puscari',
            name='job_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
